services:
  backend:
    build:
      context: ./backend
    container_name: xlsx-to-json-backend
    ports:
      - "9000:9000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:9000
    container_name: xlsx-to-json-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
